# Generated by Django 2.2.6 on 2021-07-14 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0017_auto_20210714_1134'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
