# Generated by Django 2.2.6 on 2021-07-14 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0018_delete_like'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['title'], 'verbose_name_plural': 'Название групп'},
        ),
    ]
